uber/kraken

requirements-tests.txt
test/python/components.py

Fix license compliance issues.

Downgrade pyyaml

---

examples/devcluster/README.md

Update README for more details about devcluster

---

README.md

Update README with more devcluster details

---

examples/devcluster/agent_one_start_container.sh
examples/devcluster/agent_two_start_container.sh
examples/devcluster/config/origin/development.yaml

Fix devcluster configs

---

requirements-tests.txt
test/python/components.py

yyaml has compliance issue and security risk.

Remove yaml requirement in integration tests

---

lib/torrent/scheduler/announcer/announcer_test.go

Fix flakey test by increasing timeout

---

README.md

Details are included in examples dir.

Shorten k8s section on README

---

.travis.yml

Remove Go 1.11.4 integration test

---

docs/CONFIGURATION.md
lib/backend/constants.go
lib/backend/gcsbackend/client.go
lib/backend/gcsbackend/client_test.go
lib/backend/gcsbackend/config.go
lib/backend/gcsbackend/gcs.go

Previous change #180 didn't run go fmt.

Fix GCS backend code format and update docs

---

README.md
docs/CONFIGURATION.md

Document ECR

---

.travis.yml

This is modeled after the travis tests in Makisu.

Travis: Split out tests into their own stages

---

agent/cmd/cmd.go
agent/cmd/config.go
go.mod
go.sum
lib/dockerdaemon/cli.go
lib/dockerdaemon/config.go

Move docker daemon config to a separate struct under dockerdaemon package

---

docker/agent/Dockerfile
docker/build-index/Dockerfile
docker/herd/Dockerfile
docker/origin/Dockerfile
docker/proxy/Dockerfile
docker/testfs/Dockerfile
docker/tracker/Dockerfile

Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>

bump to debian 10 (buster)

---

docs/INTEGRATEWITHHARBOR.md

Configuration 'cas' should be added when using self-signed certificate

Configuration 'cas' should be added when using self-signed certificate 

---

README.md

[enhancement/docs/fixing typos] - uber/kraken - fixing readme.md

---

helm/templates/agents.yaml
helm/templates/build-index.yaml
helm/templates/origins.yaml
helm/templates/proxy.yaml
helm/templates/testfs.yaml
helm/templates/trackers.yaml
helm/values.yaml

1. Make the repository of docker image configurable for private repository
2. Fix agent service chart error

Helm chart

---

lib/torrent/scheduler/conn/handshaker.go
lib/torrent/scheduler/conn/handshaker_test.go

Handle nil pointer error caused by empty bitfield message

---

docs/CONFIGURATION.md
docs/INTEGRATEWITHHARBOR.md
docs/STYLEGUIDE.md

for better readability and fixed some small errors

(docs): enabled syntax highlighting

---

lib/store/ca_store.go
lib/store/ca_store_test.go

An upload files is a temp file with a random uuid name. The uuid name is discarded after the file is committed to the file store and should not be reused. When MoveUploadFileToCache fails, it indicates that there is a problem reading/streaming the file or the content is corrupted. We should delete the upload file regardless to avoid failed uploads accumulating on disk.

Always delete upload file after MoveUploadFileToCache

---

nginx/nginx.go

Forgot to handle stdout in my previous log path diff.

Allow overriding nginx stdout log path

---

lib/persistedretry/manager.go

Counters cannot be decremented -- in fact, decrementing a prometheus counter
will cause a panic. If we want to represent queue size, we need to use a gauge, but
this would require quite a bit of work to implement correctly (regretfully our choice to
use channels makes this much more difficult than it should). Let's just get rid of the
counters entirely since this is totally broken anyway.

Remove persistedretry queue counter

---

utils/netutil/netutil.go

Add eth2 to supported interfaces

---

lib/backend/config.go

Adding same egress defaults we have for S3 for GCS

add gcs egress defaults

---

build-index/tagserver/server_test.go
tracker/trackerserver/announce_test.go

The refactored tests assert that when a service's readiness endpoint fails, it returns an error including the URL used to call the endpoint. Currently, the URL is matched against a regex, which is not ideal. This PR replaces the regex with a normal string, which is much easier to read.

Refactor readiness tests not to use regex

---

agent/agentclient/client.go
build-index/tagclient/client.go
build-index/tagstore/store_test.go
lib/backend/constants.go
lib/backend/hdfsbackend/webhdfs/client.go
lib/backend/hdfsbackend/webhdfs/client_test.go
lib/backend/registrybackend/blobclient_test.go
lib/backend/registrybackend/tagclient_test.go
lib/blobrefresh/refresher_test.go
lib/containerruntime/dockerdaemon/cli.go
lib/hrw/fixtures.go
lib/hrw/rendezvous_test.go
lib/store/base/file_entry.go
lib/store/base/file_map.go
lib/store/base/file_op_test.go

The diff continues to fix lint issues preparing the ground for the lint activation.
- Fixing ignored errors.
- Formatting a couple of tests.

Another portion of the lint fixes
